# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.2.1'
pod 'IQKeyboardManager'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'YYKit'
pod 'Masonry'
pod 'WeChat_SDK_iOS'
pod 'MJExtension'
pod 'SDWebImage'
pod 'FDFullscreenPopGesture'

#pod 'WechatOpenSDK'
#pod 'AliPlayerSDK_iOS'
pod 'AliPlayerSDK_iOS'
pod 'DZNEmptyDataSet'

target 'VeehuiVideoSchool' do
  # Comment the next line if you don't want to use dynamic frameworks
  #
  
  #use_frameworks!

  # Pods for VeehuiVideoSchool

end
